# project definitions
project: doc_designers
audience: designers
product: all
platform: all
version: all
destination: ../doc_designers
topnav_title: Coindroids Documentation
homepage_title: Coindroids Documentation 
site_title: Coindroids Documentation
disqus_shortname: 
google_analytics: 
github_editme_path: tomjohnson1492/documentation-theme-jekyll/blob/gh-pages
# don't use a slash before or after the above path. here's how this url gets written out in page.html: https://github.com/{{site.github_editme_path}}{{page.url | replace: '.html', '.md'}}

# variables

sidebar_tagline: 
sidebar_version: version 2.0
project_file_name: doc

port: 4001

exclude:
  - doc_writer*
  - configs/
  - _site
  - di_multi*

# same for all
host: 127.0.0.1
feedback_email: contact@coindroids.com
markdown: redcarpet
print: false
theme_file: theme-blue.css
# only use suffix if you need to force index.html to display
# suffix: index.html

highlighter: pygments

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

collections:
  tooltips:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true


